name: Visual Monitor

on:
  schedule:
    - cron: "0 1 * * *"   # KST 10:00 (UTC 01:00)
    - cron: "0 9 * * *"   # KST 18:00 (UTC 09:00)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Chrome (stable)
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Capture screenshots
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: python capture.py

      - name: Commit & push screenshots
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add shots/ || true
          git commit -m "shots: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push || true

      - name: Post to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python post_to_slack.py
