name: Visual Monitor

on:
  schedule:
    - cron: "0 23 * * *"  # 매일 오전 8시 (UTC 23시는 한국 8시)
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python capture.py
